# Generated by Django 5.0.7 on 2025-05-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='class_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
