# Generated by Django 5.2 on 2025-05-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_userregister_class_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('techer_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='classroom_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='meet.userregister')),
            ],
        ),
    ]
