# Generated by Django 5.2 on 2025-05-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='join_classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_users', to='meet.create_classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_classrooms', to='meet.userregister')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
